{
	"version": 1726317306,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/camera-sheet0.png",
		"images/kokot1-sheet0.png",
		"images/ground-sheet0.png",
		"images/krev.png",
		"images/kokot_chicken-sheet0.png",
		"images/kokot_chicken-sheet1.png",
		"images/konec-sheet0.png",
		"images/pozadi-sheet0.png",
		"images/projectile-sheet0.png",
		"images/scroll_left-sheet0.png",
		"images/scroll_right-sheet0.png",
		"images/stop-sheet0.png",
		"images/kokot_chicken_2-sheet0.png",
		"images/kokot_chicken_2-sheet1.png",
		"images/zasobnik-sheet0.png",
		"images/zasobnik-sheet1.png",
		"images/zasobnik-sheet2.png",
		"images/krev_bonus.png",
		"media/dobijeni zasobniku 1.ogg",
		"media/dobijeni zasobniku 2.ogg",
		"media/dobijeni zasobniku 3.ogg",
		"media/dobijeni zasobniku 4.ogg",
		"media/dobijeni zasobniku 5.ogg",
		"media/dobijeni zasobniku 6.ogg",
		"media/prebijeni 2.ogg",
		"media/prebijeni.ogg",
		"media/vystrel 2.ogg",
		"media/vystrel.ogg",
		"media/bensound-sexy.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}