{
	"version": 1613247318,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"sprite-sheet0.png",
		"camera-sheet0.png",
		"kokot1-sheet0.png",
		"ground-sheet0.png",
		"krev.png",
		"kokot_chicken-sheet0.png",
		"kokot_chicken-sheet1.png",
		"konec-sheet0.png",
		"pozadi-sheet0.png",
		"projectile-sheet0.png",
		"scroll_left-sheet0.png",
		"scroll_right-sheet0.png",
		"stop-sheet0.png",
		"kokot_chicken_2-sheet0.png",
		"kokot_chicken_2-sheet1.png",
		"zasobnik-sheet0.png",
		"zasobnik-sheet1.png",
		"zasobnik-sheet2.png",
		"krev_bonus.png",
		"dobijeni zasobniku 1.ogg",
		"dobijeni zasobniku 2.ogg",
		"dobijeni zasobniku 3.ogg",
		"dobijeni zasobniku 4.ogg",
		"dobijeni zasobniku 5.ogg",
		"dobijeni zasobniku 6.ogg",
		"prebijeni 2.ogg",
		"prebijeni.ogg",
		"vystrel 2.ogg",
		"vystrel.ogg",
		"bensound-sexy.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}